name=CurioDrivers
version=1.0.0
author=Your Name
maintainer=Your Name <your.email@example.com>
sentence=Abstraction layer library for CurioLab program with integrated Adafruit drivers
paragraph=CurioDrivers is a library acting as an abstraction layer to be used with the CurioLab program. It is designed to make it easier and more accessible to program and test driver extensions. Includes integrated support for Adafruit GFX, SSD1306, Seesaw, NeoPixel, and BusIO libraries.
category=Device Control
url=https://github.com/Doooom20/curio-drivers
architectures=*
depends=Adafruit GFX Library, Adafruit SSD1306, Adafruit Seesaw Library, Adafruit NeoPixel, Adafruit BusIO